---
title: "Simple_sim_vignette_2"
author: "Matthew Stephens"
date: "May 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Goal

To try out some simulations that don't match the canonical covariance matrices and see if the data driven matrices help.

# Simple simulation

Just set up data 
```{r}
  library("mashr2")
  set.seed(1)
  data = simple_sims2(1000,1)
  m=mash_init(data$Bhat,data$Shat)
  mash_add_grid(m)
  
 # m = mash(data$Bhat,data$Shat) # this runs mash with just canonical covariance matrices
  mash_status(m)
```
  
  
Run 1-by-1 to add the strong signals and ed covariances
```{r}
  mash_run_1by1(m)
  mash_status(m)
  
  mash_add_strong_signals(m)
  
  mash_add_cov_ed(m) # adds covariance matrices based on extreme deconvolution, initialized from pca

  mash_fit_g(m)
  mash_compute_loglik(m) 
```

```{r}
  mash_add_cov(m) #this adds canonical covariance matrices
  mash_fit_g(m)
  mash_compute_loglik(m) 
```
```{r}
  true.U1 = cbind(c(1,1,0,0,0),c(1,1,0,0,0),rep(0,5),rep(0,5),rep(0,5))
  true.U2 = cbind(rep(0,5),rep(0,5),c(0,0,1,1,1),c(0,0,1,1,1),c(0,0,1,1,1))

  mash_add_cov_list(m,list(true.U1 = true.U1, true.U2 = true.U2))
  mash_fit_g(m)
  mash_compute_loglik(m) 
  
```


The log likelihood is not better after adding canonical covariances,
but improves slightly after adding the true matrices. This is good!


