# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extreme_deconvolution_rcpp <- function(ydata, ycovar, projection, logweights, amp, xmean, xcovar, fixamp_int, fixmean_int, fixcovar_int, tol, maxiter, likeonly, w, logfilename, splitnmerge, convlogfilename, noproj, diagerrs, noweight) {
    .Call('_mashr_extreme_deconvolution_rcpp', PACKAGE = 'mashr', ydata, ycovar, projection, logweights, amp, xmean, xcovar, fixamp_int, fixmean_int, fixcovar_int, tol, maxiter, likeonly, w, logfilename, splitnmerge, convlogfilename, noproj, diagerrs, noweight)
}

inv_chol_tri_rcpp <- function(x_mat) {
    .Call('_mashr_inv_chol_tri_rcpp', PACKAGE = 'mashr', x_mat)
}

calc_lik_rcpp <- function(b_mat, s_mat, v_mat, l_mat, U_3d, sigma_3d, logd, common_cov, n_thread = 1L) {
    .Call('_mashr_calc_lik_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, l_mat, U_3d, sigma_3d, logd, common_cov, n_thread)
}

calc_lik_precomputed_rcpp <- function(b_mat, rooti_3d, logd, common_cov, n_thread = 1L) {
    .Call('_mashr_calc_lik_precomputed_rcpp', PACKAGE = 'mashr', b_mat, rooti_3d, logd, common_cov, n_thread)
}

calc_post_rcpp <- function(b_mat, s_mat, s_alpha_mat, s_orig_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type, n_thread = 1L) {
    .Call('_mashr_calc_post_rcpp', PACKAGE = 'mashr', b_mat, s_mat, s_alpha_mat, s_orig_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type, n_thread)
}

calc_sermix_rcpp <- function(b_mat, s_mat, v_mat, vinv_3d, U_3d, Uinv_3d_drank, U0_3d, posterior_mixture_weights, posterior_variable_weights, common_cov, n_thread = 1L) {
    .Call('_mashr_calc_sermix_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, vinv_3d, U_3d, Uinv_3d_drank, U0_3d, posterior_mixture_weights, posterior_variable_weights, common_cov, n_thread)
}

fit_teem_rcpp <- function(x_mat, w_vec, U_3d, maxiter, converge_tol, eigen_tol, verbose) {
    .Call('_mashr_fit_teem_rcpp', PACKAGE = 'mashr', x_mat, w_vec, U_3d, maxiter, converge_tol, eigen_tol, verbose)
}

