# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extreme_deconvolution_rcpp <- function(ydata, ycovar, projection, logweights, amp, xmean, xcovar, fixamp_int, fixmean_int, fixcovar_int, tol, maxiter, likeonly, w, logfilename, splitnmerge, convlogfilename, noproj, diagerrs, noweight) {
    .Call('_mashr_extreme_deconvolution_rcpp', PACKAGE = 'mashr', ydata, ycovar, projection, logweights, amp, xmean, xcovar, fixamp_int, fixmean_int, fixcovar_int, tol, maxiter, likeonly, w, logfilename, splitnmerge, convlogfilename, noproj, diagerrs, noweight)
}

calc_lik_rcpp <- function(b_mat, s_mat, v_mat, l_mat, U_3d, logd, common_cov) {
    .Call('_mashr_calc_lik_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, l_mat, U_3d, logd, common_cov)
}

calc_post_rcpp <- function(b_mat, s_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type) {
    .Call('_mashr_calc_post_rcpp', PACKAGE = 'mashr', b_mat, s_mat, v_mat, l_mat, a_mat, U_3d, posterior_weights, common_cov, report_type)
}

